sudo: false
language: ruby
rvm:
  - 2.5.1
before_install: gem install bundler -v 1.16.2
deploy:
  provider: rubygems
  gem: getto-repository-sequel
  on:
    tags: true
  api_key:
    secure: "XLSSBGoExWUtl13m7nUaUlLWosB4omJxNv1RxVm1pdQUpExaX/7jKH1SUcxuROxyU04kkvphotiouWHQS+w5HZL1ch0pof3J3DyN0a572iFOZwWM1bbdDL5lYVjkjbNiJAs5qXkSVFGqK23h7XkC6X7awmfDZAF84let7hvhUwjjhJObvYFYCTQ/SuWldCncP5HHNyOUQv8YNqcyApDY0uA+kTt+NPzk8fi9ntBvaBAoJYcQgE3Eo8DtWcowDjZBWgiQJB1BuEDuIAoranyVhtpbf9KiCGoesya6kYG3SQftKi05Gi3kulf8+1AdkyG8eNB9WrawCEMzJ79mT8GX1KsC+7D4rgSdjUnniisQgGxlyTlSd4t5/cEZ1wWQDB5tE/RnES0CqNomS+DX456KtJk8kXUvytqz7UWXbANhnyuRsxtX6xS1v3chW5HF4rzLa4bP+NWpUUvxkqRtEaUN6xMdHEbhJkV4sJe1wNc1ZjZJG50p3XCapj+8qQl87i14BUcR12+tgyyCz1y+mjvUEJTxTIFrB4wn4BBzde2HzPMMDkvGOu6r04agg+YjWkfznMs1IVTDFY8aPHADeQ+MMQlLtf1XtjGiuHQkRkvj8mMQXKEZd/YSy9mCGLmQNP1OKC0kxrbd3sluO+qkK28jtwdYJbqJC9t5iSmvITAPTdw="
